### ISSUE TITLE
[auto-add-subtitle] Button selectors need updation

### ISSUE THREAD

**Issue by mvoggu** [heiseshandian/personal-docs#2]
[veed](https://www.veed.io/) seems to have made minor changes to their webpage. CSS selectors in veed parser need to be updated accordingly

Timeout on upload button:
![Screenshot from 2021-01-29 13-47-59](https://user-images.githubusercontent.com/50870617/106249661-aa501e00-6238-11eb-9313-e8c0c0d5bc4a.png)

**Comment by heiseshandian** [comment]
Thanks for your feedback, I will fix it as soon as possible.
